### ISSUE TITLE
1 July 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#142]
## Date
Wednesday 1 July 2020 - 12pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Discuss comment below posted by Junji
- [x] Duplicate calendar invites
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] @junjikatto creates an issue with a recap of the conversations we had (see comment below)

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by junjikatto** [comment]
As we are putting together the Open Source Program Office, there are opportunities to collaborate to existing projects. We want to put a minimum infrastructure and processes in place in order to contribute and we have a few questions on how to approach that at first, and then more integrated to our CI/CD and SDLC tooling.

 - How to control who can contribute to specific projects on public repos? Should we create proxy rules specific to access white listed repo URLs? As of today, no developer has access to public repos;
 - What steps should we take before whitelist a repo to be added to the white list?
 - Which controls should we implement in order to allow contribution directly from the developer's machine?
 - How to implement a simple yet effective compliance control? Should we use a git proxy whenever there's a pull request being sent to the public repo? Should we start with manual validation for IP and Data Leakage? 
 - Should we create an internal repo mirroring the public, just for the purpose of contributing? 
 - What are the best practices to create a corporate github account for contribution before we allow developers to associate their github account to our corporate account?

**Comment by bingenito** [comment]
Present

**Comment by rarkins** [comment]
+1

**Comment by clebergsilva85** [comment]
Here!

**Comment by mcleo-d** [comment]
Hello 👋
