### ISSUE TITLE
how to "auth" against FINOS roster?

### ISSUE THREAD

**Issue by tschady** [finos/open-developer-platform#58]
## Support Question

My company would like to host some services for FINOS members only, but I am not sure how to determine if a user has membership or not.  Can I leverage the cla-bot?  Or the `metadata` service?

Is this related to #2 ?  That was closed without any comment on implementation.

**Comment by mcleo-d** [comment]
Hi @tschady - It's probably worth having this conversation on an ODP call as I'd like to be discreet about FINOS member information in an open discussion thread.

The idea sounds like a sound and useful one, but we would need to investigate the possible functional and legal side affects making this an open service call. 

Are you happy for me to add to the next ODP call agenda if you can join?

Also, do you think the service you're tailoring to FINOS members could be presented at FINOS events or written about on the FINOS blog? Just a thought.

James.

**Comment by tschady** [comment]
We would like to offer it to FINOS members under a FINOS banner, and marketed as much as possible.  

I could just take the list of member companies and whitelist their domains and call it a day, I was just hoping you had something more sophisticated I could hook into.

If you'd like to consult with legal, then I suggest delaying a phone call until you have this info in hand.

**Comment by mcleo-d** [comment]
I'll ask the legal question and will get back to you 👍🏻

**Comment by maoo** [comment]
@tschady - thank you very much for this offering! I'm happy to tackle this challenge and prove that companies like yours can augment the FINOS infrastructure with additional services!

Before proposing solutions, I'd like to share some background.

We currently rely on GitHub usernames OR email addresses/(corporate)domains (defined in the `user.email` commit author) to identify our community activities.

Our internal systems crawl (daily) through the metadata of our contributors (managed by FINOS) and generates a list of GitHub usernames, email addresses and domains that are whitelisted. Such information is currently private.

Please note that this list contains FINOS members and other contributors (ie those affiliated with non-members firms and individual contributors.

Another source of authentication is [FINOS GitHub Teams](https://github.com/orgs/finos/teams), which we map 1:1 with FINOS hosted projects to provide a simpler way to define collaboration permissions for active participants; in order to be part of a FINOS Team, a user must be a [FINOS GitHub member](https://github.com/orgs/finos/people) first (either public or private); this list is managed by FINOS and represents all users that are part of a FINOS GitHub Team which are covered by a CLA with FINOS. To be clear, it does not reflect in any way the list FINOS Members individuals.

End of the background. Regarding the solution, I could think of the following way to enable what you are requesting
- Use GitHub SSO as authentication
- Only allow access to GitHub users that are part of a FINOS GitHub Team called `GreenKey ABC Service`
- Add a form (in finos.org/greenkey-abc-service) to request access, or email help@finos.org); FINOS will go through the CLA validation process, invite the user as FINOS GitHub Member and finally add the user to the `GreenKey ABC Service` GitHub Team

Based on this initial implementation, we could later try to find a way to skip the last step; I could think of a script that nightly runs and syncs the list of FINOS Members Individuals with https://github.com/orgs/finos/people ; at that point, you could safely rely on that GitHub Team to authenticate users on your end.

I hope this provides a good start to move the conversation forward, looking forward to hearing your thoughts!

**Comment by mcleo-d** [comment]
Hi @tschady,

I've had a response from the FINOS legal council and unfortunately we're unable to publish the details of our members anywhere other than the FINOS website. This includes publicly available APIs and sorted lists.

Specifically, the IP Policy agreed between the foundation and its members states, members will not grant the foundation any other right to use member trademarks or trade names.

The legal advice given is to direct you to the membership page of the FINOS website for this information so we don't risk breaking the IP clause of our membership agreements.

I hope this helps resolve the query?

James.

**Comment by tschady** [comment]
Sorry for delay, I hadn't seen the update.
Yes, it seems clear.  GitHub Teams, although a great idea, seems slightly in conflict with that guidance James.  I'll just work off the website then.

**Comment by mcleo-d** [comment]
Thanks for your understanding @tschady 👍
